trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"

  - script: python3 build_test_artifact.py
    displayName: Build test artifact

  - publish: output
    artifact: example-output
    displayName: Publish generated file
