from datetime import datetime, timezone
from pathlib import Path
import os


def main() -> None:
    output_dir = Path(os.getenv("OUTPUT_DIR", "output"))
    output_file = output_dir / "example-artifact.txt"

    output_dir.mkdir(parents=True, exist_ok=True)
    output_file.write_text(
        "\n".join(
            [
                "Hello from Azure DevOps!",
                "This file was generated by build_test_artifact.py.",
                f"Generated at: {datetime.now(timezone.utc).isoformat()}",
                f"Build ID: {os.getenv('BUILD_BUILDID', 'local-run')}",
                f"Source branch: {os.getenv('BUILD_SOURCEBRANCH', 'local')}",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    print(f"Wrote artifact file: {output_file}")


if __name__ == "__main__":
    main()
